In [247]:
import pandas as pd
from sklearn import linear_model
import numpy as np

In [152]:
dict_countries = {
    'VI_PPS_EU28_HAB,GDP,AL': 'Albania',
    'VI_PPS_EU28_HAB,GDP,AT': 'Austria',
    'VI_PPS_EU28_HAB,GDP,BA': 'Bosnia and Herzegovina',
    'VI_PPS_EU28_HAB,GDP,BE': 'Belgium',
    'VI_PPS_EU28_HAB,GDP,BG': 'Bulgaria',
    'VI_PPS_EU28_HAB,GDP,CH': 'Switzerland',
    'VI_PPS_EU28_HAB,GDP,CZ': 'Czechia',
    'VI_PPS_EU28_HAB,GDP,DE': 'Germany',
    'VI_PPS_EU28_HAB,GDP,DK': 'Denmark',
    'VI_PPS_EU28_HAB,GDP,EE': 'Estonia',
    'VI_PPS_EU28_HAB,GDP,ES': 'Spain',
    'VI_PPS_EU28_HAB,GDP,FI': 'Finland',
    'VI_PPS_EU28_HAB,GDP,FR': 'France',
    'VI_PPS_EU28_HAB,GDP,HR': 'Croatia',
    'VI_PPS_EU28_HAB,GDP,HU': 'Hungary',
    'VI_PPS_EU28_HAB,GDP,IE': 'Ireland',
    'VI_PPS_EU28_HAB,GDP,IT': 'Italy',
    'VI_PPS_EU28_HAB,GDP,LT': 'Latvia',
    'VI_PPS_EU28_HAB,GDP,LU': 'Luxembourg',
    'VI_PPS_EU28_HAB,GDP,LV': 'Latvia',
    'VI_PPS_EU28_HAB,GDP,MK': 'North Macedonia',
    'VI_PPS_EU28_HAB,GDP,MT': 'Malta',
    'VI_PPS_EU28_HAB,GDP,NL': 'Netherlands',
    'VI_PPS_EU28_HAB,GDP,NO': 'Norway',
    'VI_PPS_EU28_HAB,GDP,PL': 'Poland',
    'VI_PPS_EU28_HAB,GDP,PT': 'Portugal',
    'VI_PPS_EU28_HAB,GDP,RO': 'Romania',
    'VI_PPS_EU28_HAB,GDP,RS': 'Serbia',
    'VI_PPS_EU28_HAB,GDP,SE': 'Sweden',
    'VI_PPS_EU28_HAB,GDP,SI': 'Slovenia',
    'VI_PPS_EU28_HAB,GDP,SK': 'Slovakia',
    'VI_PPS_EU28_HAB,GDP,UK': 'United Kingdom'
}

def translate_countries(shortcut):
    return dict_countries[shortcut]

In [153]:
gdp = pd.read_csv('gdp.tsv', sep='\t')

In [154]:
gdp.head()

na_item,ppp_cat,geo\time  2007   2008   2009   2010   2011   2012   2013   \
0   VI_PPS_EU28_HAB,GDP,AL     23     25     27     29     29     30     29   
1   VI_PPS_EU28_HAB,GDP,AT    125    125    127    126    128    132    131   
2   VI_PPS_EU28_HAB,GDP,BA     27     29     30     29     30     30     30   
3   VI_PPS_EU28_HAB,GDP,BE    117    115    118    120    119    121    120   
4   VI_PPS_EU28_HAB,GDP,BG     40     43     43     44     45     46     45   

   2014   2015   2016   2017   2018   
0     30     30     30     30     31  
1    130    129    128    127    127  
2     30     30     31     31     31  
3    119    118    118    116    115  
4     47     47     48     49     50

In [155]:
gdp.rename(columns=lambda x: x.strip(), inplace=True)
gdp.columns

Index(['na_item,ppp_cat,geo\time', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018'],
      dtype='object')

In [156]:
gdp.rename(columns={'na_item,ppp_cat,geo\\time':'Country'}, inplace=True)

In [157]:
gdp['Country'] = gdp['Country'].apply(translate_countries)

In [158]:
gdp

Country  2007  2008  2009  2010  2011  2012  2013  2014  \
0                  Albania    23    25    27    29    29    30    29    30   
1                  Austria   125   125   127   126   128   132   131   130   
2   Bosnia and Herzegovina    27    29    30    29    30    30    30    30   
3                  Belgium   117   115   118   120   119   121   120   119   
4                 Bulgaria    40    43    43    44    45    46    45    47   
5              Switzerland   156   158   160   159   162   164   165   165   
6                  Czechia    82    84    85    83    83    82    84    86   
7                  Germany   117   117   117   120   123   124   124   126   
8                  Denmark   123   125   125   129   128   127   128   128   
9                  Estonia    69    68    63    65    71    74    75    77   
10                   Spain   103   101   100    96    92    91    89    90   
11                 Finland   119   121   117   116   117   115   113   110   
12                  France   108   106   108   108   108   107   108   107   
13                 Croatia    61    63    62    59    60    60    60    59   
14                 Hungary    60    63    64    65    66    66    67    68   
15                 Ireland   148   134   129   130   130   131   132   136   
16                   Italy   107   106   106   104   104   101    98    96   
17                  Latvia    60    63    56    60    66    70    73    75   
18              Luxembourg   265   262   255   257   265   260   261   269   
19                  Latvia    57    59    52    53    57    60    62    63   
20         North Macedonia    30    32    34    34    34    34    35    36   
21                   Malta    79    79    81    83    82    84    85    89   
22             Netherlands   139   140   138   135   134   134   135   131   
23                  Norway   177   187   172   174   179   186   184   176   
24                  Poland    53    55    59    62    65    67    67    67   
25                Portugal    81    81    82    82    77    75    76    77   
26                 Romania    43    51    52    51    52    54    54    55   
27                  Serbia    35    38    39    38    40    40    40    39   
28                  Sweden   128   127   123   125   126   127   125   124   
29                Slovenia    87    90    85    83    83    82    82    82   
30                Slovakia    67    71    71    74    74    76    76    77   
31          United Kingdom   112   110   108   108   106   108   108   109   

    2015  2016  2017  2018  
0     30    30    30    31  
1    129   128   127   127  
2     30    31    31    31  
3    118   118   116   115  
4     47    48    49    50  
5    165   160   156   157  
6     87    88    89    90  
7    124   124   124   123  
8    127   126   128   126  
9     76    77    79    81  
10    91    91    92    91  
11   109   109   109   110  
12   106   104   104   104  
13    59    61    62    63  
14    68    67    68    70  
15   178   177   181   187  
16    95    97    96    95  
17    75    75    78    81  
18   266   260   253   254  
19    64    64    67    70  
20    36    37    36    38  
21    93    95    98    98  
22   130   128   128   129  
23   156   145   146   150  
24    69    68    70    71  
25    77    77    77    76  
26    56    59    63    64  
27    39    39    39    40  
28   125   122   121   121  
29    82    83    85    87  
30    77    77    76    78  
31   109   107   106   104

In [159]:
migrants = pd.read_csv('International-migrant-stock-at-mid-year.csv')

In [160]:
migrants.rename(columns={'Major area, region, country or area of destination':'Country'}, inplace=True)
migrants.sort_values('Country', inplace=True)
migrants = migrants.drop(['Sort order', 'Notes', 'Code', 'Type of data (a)'], axis=1)

In [223]:
def remove_whitespaces_cast_to_int(item):
    if isinstance(item, str):
        return int(item.replace(chr(160), ''))
    else:
        return item

cols = ['1990', '1995', '2000', '2005', '2010', '2015', '2019']

for col in cols:
    migrants[col] = migrants[col].apply(remove_whitespaces_cast_to_int)

In [224]:
migrants

Country     1990     1995     2000     2005     2010  \
16                 Albania    66013    71354    76695    64739    52784   
26                 Austria   793239   894893   996547  1136270  1275992   
27                 Belgium  1280583  1288003  1268368  1248733  1503806   
17  Bosnia and Herzegovina    56000    69476    82952    47272    38792   
0                 Bulgaria    21510    32435    43360    61074    76287   
18                 Croatia   475438   674085   585298   579273   573248   
1                  Czechia   110394   165592   220789   322540   398493   
6                  Denmark   235189   303108   371026   440383   500772   
7                  Estonia   381997   315755   249512   233701   217890   
8                  Finland    63255    99729   136203   192169   228481   
28                  France  5897267  6087993  6278718  6737600  7309986   
29                 Germany  5936181  7464406  8992631  9402447  9812263   
2                  Hungary   347510   322234   296957   366787   436616   
9                  Iceland     9584    12738    15892    25492    35091   
10                 Ireland   227961   226892   350552   589046   730542   
19                   Italy  1428219  1774954  2121688  3954790  5787893   
11                  Latvia   646007   538093   430178   376725   313786   
12               Lithuania   349258   273587   214311   201209   160772   
30              Luxembourg   113795   126106   139750   150618   163142   
20                   Malta    15077    17740    21521    24560    33008   
31             Netherlands  1182263  1346164  1556337  1736127  1832510   
21         North Macedonia    95142   109343   125665   127667   129701   
13                  Norway   192587   233302   292440   361144   526799   
3                   Poland  1127771   964725   825251   722509   642417   
22                Portugal   435782   532822   651472   771184   762825   
4                  Romania   135825   135037   134254   145162   177211   
23                  Serbia    99269   870980   977873   854848   826275   
5                 Slovakia    41295    69323   116376   130491   146319   
24                Slovenia   178077   174419   214508   217218   253786   
25                   Spain   821605  1020067  1657285  4107226  6280065   
14                  Sweden   788767   936022  1003798  1125790  1384929   
32             Switzerland  1392282  1478829  1570756  1805437  2075182   
15          United Kingdom  3650286  4155293  4730165  5926156  7119664   

        2015      2019  
16     52031     49160  
26   1492374   1779857  
27   1783488   1981919  
17     38574     35735  
0     123803    168516  
18    561093    518083  
1     416454    512705  
6     595876    722878  
7     194664    190242  
8     314856    383116  
28   7874172   8334875  
29  10220418  13132146  
2     475508    512043  
9      39072     52404  
10    759256    833564  
19   5805328   6273722  
11    265418    237266  
12    136021    117218  
30    248888    291723  
20     52642     84949  
31   1996318   2282791  
21    130730    131175  
13    746375    867765  
3     619403    655985  
22    864814    888162  
4     281048    462552  
23    807441    820312  
5     177624    187984  
24    237616    253122  
25   5891208   6104203  
14   1676264   2005210  
32   2416394   2572029  
15   8411569   9552110

So, in an extremely simple model, we have an equation in a form:
coeff[0] * gdp[2010] = migrants[2010]
coeff[0] * gdp[2015] = migrants[2015]
coeff[0] * gdp[2018] = migrants[2019]

and then we set coeff[0] to minimize squared errors
PLEASE NOTE THAT WE DON'T HAVE gdp data for 2019 year (only 2018)!

when we add another factor, e.g. underemployment it would look like this:
coeff[0] * gdp[2010] + coeff[1] * uempl[2010] = migrants[2010]
coeff[0] * gdp[2015] + coeff[1] * uempl[2015] = migrants[2015]
coeff[0] * gdp[2018] + coeff[1] * uempl[2018] = migrants[2019]
etc.

In [226]:
albGdp = gdp.loc[gdp['Country'] == 'Albania']
albMig = migrants.loc[migrants['Country'] == 'Albania']

In [237]:
gdp2007 = albGdp.iloc[0]['2007']
gdp2011 = albGdp.iloc[0]['2011']
gdp2016 = albGdp.iloc[0]['2016']
migr2005 = albMig.iloc[0]['2005']
migr2010 = albMig.iloc[0]['2010']
migr2015 = albMig.iloc[0]['2015']
migr2019 = albMig.iloc[0]['2019']

In [259]:
xtrain = np.array([migr2005, migr2010, migr2015]).reshape(-1, 1)
ytrain = np.array([gdp2007, gdp2011, gdp2016]).reshape(-1, 1)
xtest = np.array([migr2019]).reshape(-1, 1)
xtrain

array([[64739],
       [52784],
       [52031]])

In [260]:
regr = linear_model.LinearRegression()
regr.fit(xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [261]:
regr.coef_

array([[-0.00052934]])

In [262]:
regr.predict(xtest)

array([[31.2282091]])